language: python
python:
  - "3.6"

sudo: required
dist: trusty

notifications:
  email: false

before_install:   
  - "sudo apt-get update || true"
  
install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION 
  - conda activate test-environment
  
  # dependencies
  - "sudo apt-get install -qq python-tk scons git || true"
  - "conda install numpy matplotlib tensorflow scikit-learn || true" 
  - "conda list"

before_script:
  - python --version
  - python3 --version
  - python2 --version

script:
  - export PYTHONPATH=`pwd`/scripts
  - echo ====== New auto-test ======
  - cd examples/auto_test && python main.py -
  #- mkdir -p examples/mnist-densenet/tmp
  #- echo ====== local NNOM test ======
  #- cd examples/mnist-densenet && python model/mnist_densenet.py && cp -v weights.h mcu && scons && NNOM_TEST_ON_CI=YES python model/mnist_densenet.py && cd -
  #- echo ====== CMSIS NN NNOM test ======
  #- cd examples/mnist-densenet && USE_CMSIS_NN=YES scons && NNOM_TEST_ON_CI=YES python model/mnist_densenet.py && cd -

env:
- NNOM_ON_CI=YES
